<template>
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>Token</th>
        <th>Native Chain</th>
        <th>Faucet</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>LINK</td>
        <td>Rinkeby</td>
        <td>
          <a
            href="https://faucets.chain.link/rinkeby"
            target="_blank"
          >
            here
          </a>
        </td>
      </tr>
      <tr>
        <td>ETH</td>
        <td>Rinkeby</td>
        <td>
          <a
            href="https://faucets.chain.link/rinkeby"
            target="_blank"
          >
            here
          </a>
        </td>
      </tr>
      <tr>
        <td>ACME</td>
        <td>Rinkeby</td>
        <td>
          <a
            href="#"
            target="_blank"
          >
            here
          </a>
        </td>
      </tr>
    </tbody>
  </table>
</template>

<script>
export default {}
</script>
